# Generated by Django 5.0.3 on 2024-03-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_facebook_remove_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='users_profile',
        ),
    ]
