# Generated by Django 4.2.10 on 2024-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0003_remove_order_address_order_name_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
