# Generated by Django 5.0.3 on 2024-03-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - ⭐️'), (2, '2 - ⭐️⭐️'), (3, '3 - ⭐️⭐️⭐️'), (4, '4 - ⭐️⭐️⭐️⭐️'), (5, '5 - ⭐️⭐️⭐️⭐️⭐️')], null=True),
        ),
    ]
