# Generated by Django 5.0.3 on 2024-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0008_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(5, '⭐️⭐️⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (3, '⭐️⭐️⭐️'), (2, '⭐️⭐️'), (1, '⭐️')], null=True),
        ),
    ]
