# Generated by Django 5.2.4 on 2025-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0009_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='thumb',
            field=models.ImageField(default='default.png', null=True, upload_to='products/'),
        ),
    ]
